version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: /app/backend/entrypoint.sh
    env_file:
      - .env
    ports:
      - '8000:8000'
      - '8001:8001'
      - '5678:5678'
    volumes:
      - .:/app/backend
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    env_file:
      - .env

  redis:
    image: redis:latest

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: /app/backend/worker.sh
    volumes:
      - .:/app/backend
    ports:
      - '6900:6900'
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: /app/backend/beat.sh
    volumes:
      - .:/app/backend
    env_file:
      - .env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/backend/flower.sh
    volumes:
      - .:/app/backend
    env_file:
      - .env
    ports:
      - '5557:5555'
    depends_on:
      - redis
      - db
