version: '3.8'

services:
  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    command: /app/backend/entrypoint.sh
    env_file:
      - ./.env

    ports:
      - '8000:8000'

    volumes:
      - .:/app/backend

    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
      
volumes:
  postgres_data: