version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: /home/app/backend/entrypoint.prod.sh
    volumes:
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media
    expose:
      - 8000
    env_file:
      - ./prod.env

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: /home/app/backend/worker.sh
    volumes:
      - .:/home/app/backend
    env_file:
      - ./prod.env

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: /home/app/backend/beat.sh
    volumes:
      - .:/home/app/backend
    env_file:
      - ./prod.env

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=${CELERY_BROKER}', '--port=5555']
    env_file:
      - ./prod.env
    ports:
      - '5557:5555'

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media
      - ./letsencrypt/:/etc/letsencrypt/
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - backend
      - flower
  
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  postgres_data:
  static_volume:
  media_volume: