version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: /entrypoint
    env_file:
      - .env

    ports:
      - '8000:8000'

    volumes:
      - .:/app/backend

    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:latest

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app/backend
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app/backend
    env_file:
      - .env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    image: celery_flower
    command: /start-flower
    volumes:
      - .:/app/backend
    env_file:
      - .env
    ports:
      - '5557:5555'
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
