version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sudo /app/backend/entrypoint.sh
    env_file:
      - .env

    ports:
      - '8000:8000'

    volumes:
      - .:/app/backend

    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:latest

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: celery_worker
    command: sudo /app/backend/worker.sh
    volumes:
      - .:/app/backend
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: celery_beat
    command: sudo /app/backend/beat.sh
    volumes:
      - .:/app/backend
    env_file:
      - .env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    image: celery_flower
    command: sudo /app/backend/flower.sh
    volumes:
      - .:/app/backend
    env_file:
      - .env
    ports:
      - '5557:5555'
    depends_on:
      - redis
      - db

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  postgres_data:
