# Generated by Django 4.1.6 on 2023-12-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="postcomment",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
