# Generated by Django 4.1.6 on 2023-05-10 02:42

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=post.models.upload_file_comment_post_directory_path),
        ),
    ]
