# Generated by Django 4.1.6 on 2023-05-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinteraction',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('haha', 'Haha'), ('love', 'Love'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry'), ('UNLIKE', 'Unlike')], default='UNLIKE', max_length=255),
        ),
    ]
