# Generated by Django 4.1.6 on 2023-05-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postinteraction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('friends', 'Friends'), ('specificFriends', 'Specific Friends'), ('friendExcepts', 'Friend Excepts')], default='public', max_length=255),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('haha', 'Haha'), ('love', 'Love'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry'), ('unlike', 'Unlike')], default='unlike', max_length=255),
        ),
    ]
