# Generated by Django 4.1.6 on 2023-04-07 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receiverId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverNotification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='senderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderNotification', to=settings.AUTH_USER_MODEL),
        ),
    ]
