# Generated by Django 4.1.6 on 2023-04-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0004_notification_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
