# Generated by Django 4.1.6 on 2023-04-12 04:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0005_notification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="linkUrl",
        ),
    ]
