# CircleCI configuration file
version: 2.1


orbs:
  browser-tools: circleci/browser-tools@1.4.1
  docker: circleci/docker@2.2.0
  jira: circleci/jira@1.3.1


executors:
  backend-executor:
    docker:
      - image: cimg/python:3.10
      - image: cimg/redis:7.0
      - image: cimg/postgres:15.0
        environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres


jobs:
  # Job one with a unique name
  check-lint:
    executor: backend-executor
    steps:
      - checkout
      - run:
          name: Install Lint packages
          command: |
            pip install flake8
      - run:
          name: Check Lint
          command: |
            flake8 .




  test-backend:
    executor: backend-executor
    environment:
      DEBUG: 1
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      ENVIRONMENT: local
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgress && exit 1
      - run:
          name: Migrations and Migrate
          command: |
            pip install -r requirements.txt
            python manage.py makemigrations
            python manage.py migrate
      - run:
          name: Run unit test
          command: |
            pip install coverage
            pip install pytest-django
            coverage run -m pytest --junitxml=test-results/junit.xml
            coverage html
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov

  deploy-prod:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "59:49:79:51:6d:cc:b8:d1:17:b6:2f:af:cd:ea:12:15"
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy.sh"

  deploy-prod-2:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "59:49:79:51:6d:cc:b8:d1:17:b6:2f:af:cd:ea:12:15"
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER_2@$DROPLET_IP_2 "./deploy.sh"

workflows:
  # Name of workflow
  pipeline:
    # List of jobs that will run
    jobs:
      - check-lint
      - test-backend
      - deploy-prod:
          requires:
            - test-backend
            - check-lint
          filters:
            branches:
              only:
                - main
      - deploy-prod-2:
          requires:
            - test-backend
            - check-lint
          filters:
            branches:
              only:
                - deploy/kltndemo