# Generated by Django 4.1.6 on 2023-05-31 23:23

from django.db import migrations

import chat.models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomchat",
            name="roomAvatar",
            field=chat.models.AvatarRoomField(blank=True, max_length=255, null=True),
        ),
    ]
