# Generated by Django 4.1.6 on 2023-04-26 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchat',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
