# Generated by Django 4.1.6 on 2023-04-28 08:45

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchat',
            name='roomAvatar',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.upload_room_avatar_directory_path),
        ),
    ]
