# Generated by Django 4.1.6 on 2023-12-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_roomchat_roomavatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="roomchat",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
