# Generated by Django 4.1.6 on 2023-04-29 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_membership_room_chat_alter_membership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='chat.roomchat'),
        ),
    ]
