# Generated by Django 4.1.6 on 2023-04-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_file_message_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('created',)},
        ),
    ]
