# Generated by Django 4.1.6 on 2023-12-29 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_message_active_roomchat_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomChatProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identify", models.CharField(max_length=255, unique=True)),
                (
                    "roomChat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="chat.roomchat",
                    ),
                ),
            ],
        ),
    ]
