# Generated by Django 4.1.6 on 2023-04-29 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_alter_file_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='room_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_membership', to='chat.roomchat'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
