# Generated by Django 4.1.6 on 2023-04-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isRemoved',
            field=models.BooleanField(default=False),
        ),
    ]
