# Generated by Django 4.1.6 on 2023-04-18 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_isremoved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiverID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.roomchat'),
        ),
    ]
