# Generated by Django 4.1.6 on 2023-04-18 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_alter_message_receiverid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiverID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='chat.roomchat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='senderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senders', to=settings.AUTH_USER_MODEL),
        ),
    ]
