# Generated by Django 4.1.6 on 2023-04-18 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_alter_message_receiverid_alter_message_senderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiverID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_receiver', to='chat.roomchat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='senderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roomchat',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='room_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seen',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seen',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_message', to='chat.message'),
        ),
    ]
