# Generated by Django 4.1.6 on 2023-04-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_receiverid_alter_message_senderid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchat',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
