# Generated by Django 4.1.6 on 2023-04-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_roomchat_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchat',
            name='updated',
        ),
    ]
