# Generated by Django 4.1.6 on 2023-04-25 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_roomchat_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchat',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
