# Generated by Django 4.1.6 on 2023-04-12 06:22

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default/avatar_default.jpg', null=True, upload_to=user.models.upload_cover_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='default/cover_default.png', null=True, upload_to=user.models.upload_cover_directory_path),
        ),
    ]
