# Generated by Django 4.1.6 on 2023-04-12 06:44

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar_alter_user_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default/avatar_default.jpg', null=True, upload_to=user.models.upload_avatar_directory_path),
        ),
    ]
