# Generated by Django 4.1.6 on 2023-12-28 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_remove_user_mute_alter_user_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follow",
        ),
        migrations.AddField(
            model_name="profile",
            name="follow",
            field=models.ManyToManyField(
                blank=True, related_name="friend_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
