# Generated by Django 4.1.6 on 2023-12-28 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friend",
            field=models.ManyToManyField(
                blank=True, related_name="friend_user", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="follow",
            field=models.ManyToManyField(
                blank=True, related_name="follow_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
