# Generated by Django 4.1.6 on 2023-12-28 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_profile_friend_alter_profile_follow"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="AdditionalProfile",
        ),
    ]
